version: '2'

services:

  voip:
    image: ghcr.io/izer-xyz/3cx:latest
    restart: unless-stopped
    tty: true # get systemd to log to console
    volumes:
      - /etc/localtime:/etc/localtime:ro # set time to the host time
      - tmp:/tmp # systemd 
      - run:/run # systemd
      - lock:/run/lock # systemd
      - voip:/mnt/voip # persistent storage
      - /sys/fs/cgroup:/sys/fs/cgroup:ro #systemd
    ports:
      - "5015:5015" # setup
      - "5090:5090"
      - "5090:5090/udp"
    labels:
      traefik.enable: true
      traefik.http.services.voip.loadbalancer.server.port: 5000 # default 3cx http port
      
volumes:
  voip:
  tmp:
    driver_opts:
      type: tmpfs
      device: tmpfs
  run:
    driver_opts:
      type: tmpfs
      device: tmpfs
  lock:
    driver_opts:
      type: tmpfs
      device: tmpfs
